# Generated by Django 4.2.4 on 2023-08-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=83, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination', 'distance')},
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('source', 'destination', 'distance'), name='unique_source_destination_distance'),
        ),
    ]
