# Generated by Django 4.2.4 on 2023-09-01 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journey',
            name='crew',
            field=models.ManyToManyField(related_name='journeys', to='train.crew'),
        ),
        migrations.AddField(
            model_name='journey',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='train.route'),
        ),
        migrations.AddField(
            model_name='journey',
            name='train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='train.train'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('cargo', 'seat', 'journey'), name='unique_cargo_seat_journey'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('cargo', 'seat', 'journey')},
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('source', 'destination', 'distance'), name='unique_source_destination_distance'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination', 'distance')},
        ),
    ]
