# Generated by Django 4.2.4 on 2023-08-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_alter_station_name_alter_route_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='crew',
            field=models.ManyToManyField(related_name='journeys', to='train.crew'),
        ),
    ]
